#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef NSURE_SWIFT_H
#define NSURE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="nSure",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import nSure_Private;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="nSure",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class NSureResolvedConfig;
SWIFT_CLASS("_TtC5nSure19NSureConfigResolver")
@interface NSureConfigResolver : NSObject
+ (NSureResolvedConfig * _Nonnull)resolveWithJson:(NSDictionary<NSString *, id> * _Nonnull)json appId:(NSString * _Nonnull)appId partnerId:(NSString * _Nullable)partnerId sdkVersion:(NSString * _Nonnull)sdkVersion osVersion:(NSString * _Nonnull)osVersion deviceId:(NSString * _Nonnull)deviceId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Production implementation of NSureCrashSubsystemHooks. Exposed to
/// NSure.m as the <code>@objc(NSureCrashProductionHooks)</code> class with the
/// <code>+productionDefault</code> class method.
/// Declared <code>public</code> so the class name and the <code>+productionDefault</code> entry
/// point appear in the generated <code>nSure-Swift.h</code> header that NSure.m
/// consumes. Internal visibility would suppress it from the header even
/// though the ObjC runtime can still see it at launch time — NSure.m
/// compiles before Swift runs, so “unseen by ObjC header” = “unknown
/// identifier at compile time”. Matches the pattern already used by
/// NSureLogObjC in the same target.
SWIFT_CLASS_NAMED("NSureCrashProductionHooks")
@interface NSureCrashProductionHooks : NSObject <NSureCrashSubsystemHooks>
/// Return a fresh production hooks instance. NSure.m caches the result
/// for the lifetime of the process.
+ (NSureCrashProductionHooks * _Nonnull)productionDefault SWIFT_WARN_UNUSED_RESULT;
/// Explicit public no-argument initializer so the generated ObjC
/// interface exposes <code>-[NSureCrashProductionHooks init]</code> (the
/// <code>+productionDefault</code> factory is the real entry point — this exists
/// only so the class is instantiable from ObjC if a consumer ever
/// needs it).
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)checkVersionRecovery;
- (void)markPreviousLaunchCrashedIfNeeded;
- (void)bumpLaunchCounter;
- (BOOL)isInSafeMode SWIFT_WARN_UNUSED_RESULT;
- (void)emitSafeModeEvent;
- (void)markSDKDisabled;
- (void)snapshotBinaryImages;
- (BOOL)initFastWriter SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (void)deliverPendingCrashes;
/// Resolved URL: sandbox iff the configured app id starts with
/// <code>sandbox</code> (case-insensitive). Same heuristic NSure.m uses to set
/// <code>_isProduction</code> and <code>_serverURL</code>. The app id is read from the
/// Objective-C global <code>NSURE_APP_ID</code> via <code>NSureCrashAppIdBridge_currentAppId</code>
/// so production and tests share the same UTF-8 bridge path.
+ (NSString * _Nonnull)reportSdkMsgURL SWIFT_WARN_UNUSED_RESULT;
/// Test-only: pin the appId used for endpoint resolution. Pass nil
/// to clear. Used by the wiring tests.
+ (void)setAppIdOverrideForTests:(NSString * _Nullable)id;
/// Test-only: pin the resolved URL directly. Used by coexistence
/// tests that exercise the full wiring against a stub poster.
+ (void)setReportSdkMsgURLOverrideForTests:(NSString * _Nullable)url;
- (BOOL)installCrashHandlers SWIFT_WARN_UNUSED_RESULT;
- (void)uninstallCrashHandlers;
- (void)emitAppInitDone;
@end

@interface NSureCrashProductionHooks (SWIFT_EXTENSION(nSure))
+ (void)refreshKSCrashUserInfo;
@end

/// Small utility for SDK-wide environment queries.
SWIFT_CLASS_NAMED("NSureEnvironment")
@interface NSureEnvironment : NSObject
/// Returns <code>true</code> when the given app ID denotes a sandbox environment.
/// The heuristic is identical across iOS and Android: a
/// case-insensitive “sandbox” prefix on the app ID string.
+ (BOOL)isSandboxAppId:(NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5nSure23NSureFingerprintManager")
@interface NSureFingerprintManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSureFingerprintManager * _Nonnull shared;)
+ (NSureFingerprintManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Returns the cached requestId, or nil if not yet available or failed.
@property (nonatomic, readonly, copy) NSString * _Nullable currentFpRequestId;
/// True once start() or startWithApiKey(_:) has been called.
@property (nonatomic, readonly) BOOL isStarted;
/// Start fingerprint fetch. Uses the provided remote config key if non-empty,
/// otherwise falls back to the default key. Idempotent — second call is a no-op.
- (void)start;
/// Underlying fetch method. Called by start() in production and directly by tests.
/// \param apiKey FingerprintPro public API key.
///
- (void)startWithApiKey:(NSString * _Nonnull)apiKey;
/// Wait until the fingerprint state settles (.available or .failed), or until
/// <code>timeout</code> seconds elapse — whichever comes first. The completion block is
/// called exactly once on a background queue.
/// If state is already settled when called, <code>completion</code> fires immediately
/// (asynchronously on a global queue to avoid deadlocks).
- (void)waitForReadinessWithTimeout:(NSTimeInterval)timeout completion:(void (^ _Nonnull)(void))completion;
/// When non-nil, called instead of FingerprintProFactory in performFetch.
/// Use in pre-commit / CODE_SIGNING_ALLOWED=NO environments where
/// FingerprintPro’s Keychain init crashes (missing entitlements).
@property (nonatomic, copy) void (^ _Nullable testFetchBlock)(void);
/// Simulate a successful fingerprint fetch result. For unit tests only.
/// Also drains any pending waitForReadiness callbacks.
- (void)testInjectResultWithVisitorId:(NSString * _Nonnull)visitorId requestId:(NSString * _Nonnull)requestId;
/// Simulate a failed fingerprint fetch. For unit tests only.
/// Also drains any pending waitForReadiness callbacks.
- (void)testInjectFailure;
@property (nonatomic, readonly) NSInteger testPendingReadinessCallbackCount;
- (void)testFirePendingReadinessCallbacks;
/// Reset the manager to its initial state. For unit tests only.
/// Discards any pending callbacks without firing them. Preserves
/// <code>testFetchBlock</code> so the next start() call cannot reach real FP.
- (void)testReset;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, NSureLogLevel)
@protocol NSureLogDelegate;
SWIFT_CLASS_NAMED("NSureLog")
@interface NSureLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)setLogLevel:(enum NSureLogLevel)level;
/// Clear the remote log level override, reverting to the local ceiling.
+ (void)clearRemoteLevel;
+ (void)setLogDelegate:(id <NSureLogDelegate> _Nullable)delegate;
/// Returns true if a message at <code>level</code> would pass the current threshold.
+ (BOOL)isEnabledFor:(enum NSureLogLevel)level SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, NSureLogCategory, open) {
  NSureLogCategoryCore = 0,
  NSureLogCategoryConfig = 1,
  NSureLogCategorySession = 2,
  NSureLogCategoryEvents = 3,
  NSureLogCategoryNetwork = 4,
  NSureLogCategoryFingerprint = 5,
  NSureLogCategoryLifecycle = 6,
  NSureLogCategoryCrash = 7,
  NSureLogCategoryRemoteLog = 8,
};

SWIFT_PROTOCOL("_TtP5nSure16NSureLogDelegate_")
@protocol NSureLogDelegate
- (void)nsureLogWithLevel:(enum NSureLogLevel)level category:(enum NSureLogCategory)category message:(NSString * _Nonnull)message;
@end

typedef SWIFT_ENUM(NSInteger, NSureLogLevel, open) {
  NSureLogLevelOff = -1,
  NSureLogLevelError = 0,
  NSureLogLevelWarning = 1,
  NSureLogLevelInfo = 2,
  NSureLogLevelDebug = 3,
  NSureLogLevelVerbose = 4,
};

SWIFT_CLASS_NAMED("NSureLogObjC")
@interface NSureLogObjC : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// General log method. Guards against invalid enum raw values from ObjC callers.
/// The message parameter is declared optional to safely handle ObjC callers passing nil
/// (which can happen despite nonnull annotations when callers silence the warning).
+ (void)logWithLevel:(enum NSureLogLevel)level category:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logError:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logWarning:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logInfo:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logDebug:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logVerbose:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
@end

@protocol NSureRemoteConfigListener;
@class NSURLSessionConfiguration;
@class NSData;
SWIFT_CLASS("_TtC5nSure23NSureMobileRemoteConfig")
@interface NSureMobileRemoteConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSureMobileRemoteConfig * _Nonnull sharedInstance;)
+ (NSureMobileRemoteConfig * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Register a listener for live config updates. Double-add is a
/// no-op (object identity check). Thread-safe.
- (void)addConfigListener:(id <NSureRemoteConfigListener> _Nonnull)listener;
/// Unregister a previously added listener. Thread-safe.
- (void)removeConfigListener:(id <NSureRemoteConfigListener> _Nonnull)listener;
/// Visible for tests — snapshot the current listener count so tests
/// can assert registration without reaching through reflection.
- (NSInteger)configListenerCountForTests SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) NSureResolvedConfig * _Nonnull resolvedConfig;
@property (nonatomic) BOOL isSDKEnabled;
@property (nonatomic, readonly) BOOL off;
@property (nonatomic, readonly) BOOL merchantOff;
@property (nonatomic, readonly) BOOL platformOff;
@property (nonatomic, readonly) BOOL partnerOff;
- (BOOL)isOff SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
@property (nonatomic, copy) NSString * _Nonnull partnerId;
/// URLSession configuration used for config fetches.
/// Uses .default so globally registered URLProtocol subclasses are picked up at call time.
@property (nonatomic, strong) NSURLSessionConfiguration * _Nonnull urlSessionConfiguration;
/// Set this before SDK init to bypass network fetch and use a local JSON dictionary.
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable localConfigOverride;
- (void)fetchRemoteConfigWith:(NSString * _Nonnull)appId configUrl:(NSString * _Nullable)configUrl fallbackConfigUrl:(NSString * _Nullable)fallbackConfigUrl completion:(void (^ _Nullable)(void))completion;
- (void)parseRemoteConfig:(NSDictionary<NSString *, id> * _Nonnull)dict;
/// Hard size cap for remote-config payloads. Bodies over this are rejected
/// without parsing to bound memory/CPU on a hostile or misbehaving server.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger maxConfigBytes;)
+ (NSInteger)maxConfigBytes SWIFT_WARN_UNUSED_RESULT;
/// Test-only wrapper that exposes the private parser to ObjC tests.
+ (NSDictionary<NSString *, id> * _Nullable)parseConfigJSONForTesting:(NSData * _Nonnull)data source:(NSString * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC5nSure19NSureNetworkMonitor")
@interface NSureNetworkMonitor : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSureNetworkMonitor * _Nonnull shared;)
+ (NSureNetworkMonitor * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)startMonitoringWithCallback:(void (^ _Nonnull)(BOOL))callback;
@end

/// Listener protocol for subsystems that need to react to remote-config
/// updates at runtime (not just the one-shot post-init callback). Fires
/// after <code>resolvedConfig</code> has been updated and all side-effects inside
/// <code>parseRemoteConfig</code> / <code>loadFromCacheOrMinimumMode</code> have run, on the
/// main thread (the parse path always dispatches to main).
/// Listeners MUST NOT raise — any exception is caught and NSLogged
/// inside <code>fireConfigUpdated(_:)</code> so the config pipeline cannot be
/// broken by a buggy subscriber.
SWIFT_PROTOCOL("_TtP5nSure25NSureRemoteConfigListener_")
@protocol NSureRemoteConfigListener
- (void)onRemoteConfigUpdated:(NSureResolvedConfig * _Nonnull)resolved;
@end

@class NSNumber;
/// Resolved feature configuration after three-level merge.
/// Properties use internal(set) — tests configure state via parseRemoteConfig with JSON dicts.
SWIFT_CLASS("_TtC5nSure19NSureResolvedConfig")
@interface NSureResolvedConfig : NSObject
@property (nonatomic, readonly) BOOL keepAlive;
@property (nonatomic, readonly) BOOL printScreen;
@property (nonatomic, readonly) BOOL fingerprint;
@property (nonatomic, readonly) BOOL sessionTracking;
/// Crash reporting defaults OFF (opt-in): the SDK must NOT install
/// crash handlers until remote config explicitly turns the flag on.
/// Mirrors Android NSureConfigResolver.Feature.CRASH_REPORTING.defaultValue=false.
@property (nonatomic, readonly) BOOL crashReporting;
@property (nonatomic, readonly) BOOL remoteLogging;
@property (nonatomic, readonly) NSInteger keepAliveRolloutPercent;
@property (nonatomic, readonly) NSInteger printScreenRolloutPercent;
@property (nonatomic, readonly) NSInteger fingerprintRolloutPercent;
@property (nonatomic, readonly) NSInteger sessionTrackingRolloutPercent;
@property (nonatomic, readonly) NSInteger crashReportingRolloutPercent;
@property (nonatomic, readonly) NSInteger remoteLoggingRolloutPercent;
@property (nonatomic, readonly) NSInteger appActivationRate;
@property (nonatomic, readonly, copy) NSString * _Nonnull eventsReportUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull fingerprintApiKey;
/// Remote-config log level. nil means no logLevel was specified in config.
/// Stored as NSNumber wrapping the raw Int of NSureLogLevel because @objc
/// does not support Optional<enum>.
@property (nonatomic, readonly, strong) NSNumber * _Nullable logLevelRaw;
/// Resolved <code>verbosityReportingRate</code>. nil means the feature is inactive
/// (key absent / unparseable / suppressed on kill path). When set, the
/// value is clamped to [0, 100]. Applied as a one-shot session roll at
/// the first config where the key appears.
@property (nonatomic, readonly, strong) NSNumber * _Nullable verbosityReportingRate;
/// Resolver-derived kill-switch booleans. Set to true when the
/// corresponding layer’s <code>off</code> flag was true in the config JSON that
/// produced this resolution. These are the authoritative kill signals
/// consumed by <code>NSureMobileRemoteConfig.applyResolvedSideEffects</code> —
/// they are NOT the persisted flags read back from UserDefaults.
@property (nonatomic, readonly) BOOL globalOff;
@property (nonatomic, readonly) BOOL merchantOff;
@property (nonatomic, readonly) BOOL platformOff;
@property (nonatomic, readonly) BOOL partnerOff;
+ (NSureResolvedConfig * _Nonnull)minimumModeConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5nSure23NSureScreenshotDetector")
@interface NSureScreenshotDetector : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSureScreenshotDetector * _Nonnull shared;)
+ (NSureScreenshotDetector * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Called whenever a screenshot is taken.
@property (nonatomic, copy) void (^ _Nullable onScreenshotTaken)(void);
- (void)startListening;
- (void)stopListening;
@end

SWIFT_CLASS("_TtC5nSure22NSureVersionComparator")
@interface NSureVersionComparator : NSObject
+ (enum NSComparisonResult)compare:(NSString * _Nullable)v1 with:(NSString * _Nullable)v2 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.3.2 effective-5.10 (swiftlang-6.3.2.1.108 clang-2100.1.1.101)
#ifndef NSURE_SWIFT_H
#define NSURE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif // defined(__OBJC__)
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  if __has_feature(generalized_swift_name)
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
#  else
#   define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
#  endif
# else
#  define SWIFT_ENUM(_type, _name, _extensibility) _type _name; enum 
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM_TAG)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_TAG enum
# else
#  define SWIFT_ENUM_TAG
# endif
#endif
#if !defined(SWIFT_ENUM_FWD_DECL)
# if (defined(__cplusplus) && __cplusplus >= 201103L) ||      (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 202311L) ||      __has_feature(objc_fixed_enum)
#  define SWIFT_ENUM_FWD_DECL(_type, _name) enum _name : _type;
# else
#  define SWIFT_ENUM_FWD_DECL(_type, _name) typedef _type _name;
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_AVAILABILITY_DOMAIN)
# define SWIFT_AVAILABILITY_DOMAIN(dom, ...) __attribute__((availability(domain: dom, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if !__has_feature(nullability)
# define _Nonnull
# define _Nullable
# define _Null_unspecified
#elif !defined(__OBJC__)
# pragma clang diagnostic ignored "-Wnullability-extension"
#endif
#if !__has_feature(nullability_nullable_result)
# define _Nullable_result _Nullable
#endif
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="nSure",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__cplusplus)
extern "C" {
#endif

#if defined(__cplusplus)
} // extern "C"
#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
@import nSure_Private;
#endif

#endif // defined(__OBJC__)
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="nSure",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class NSureResolvedConfig;
SWIFT_CLASS("_TtC5nSure19NSureConfigResolver")
@interface NSureConfigResolver : NSObject
+ (NSureResolvedConfig * _Nonnull)resolveWithJson:(NSDictionary<NSString *, id> * _Nonnull)json appId:(NSString * _Nonnull)appId partnerId:(NSString * _Nullable)partnerId sdkVersion:(NSString * _Nonnull)sdkVersion osVersion:(NSString * _Nonnull)osVersion deviceId:(NSString * _Nonnull)deviceId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

/// Production implementation of NSureCrashSubsystemHooks. Exposed to
/// NSure.m as the <code>@objc(NSureCrashProductionHooks)</code> class with the
/// <code>+productionDefault</code> class method.
/// Declared <code>public</code> so the class name and the <code>+productionDefault</code> entry
/// point appear in the generated <code>nSure-Swift.h</code> header that NSure.m
/// consumes. Internal visibility would suppress it from the header even
/// though the ObjC runtime can still see it at launch time — NSure.m
/// compiles before Swift runs, so “unseen by ObjC header” = “unknown
/// identifier at compile time”. Matches the pattern already used by
/// NSureLogObjC in the same target.
SWIFT_CLASS_NAMED("NSureCrashProductionHooks")
@interface NSureCrashProductionHooks : NSObject <NSureCrashSubsystemHooks>
/// Return a fresh production hooks instance. NSure.m caches the result
/// for the lifetime of the process.
+ (NSureCrashProductionHooks * _Nonnull)productionDefault SWIFT_WARN_UNUSED_RESULT;
/// Explicit public no-argument initializer so the generated ObjC
/// interface exposes <code>-[NSureCrashProductionHooks init]</code> (the
/// <code>+productionDefault</code> factory is the real entry point — this exists
/// only so the class is instantiable from ObjC if a consumer ever
/// needs it).
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (void)checkVersionRecovery;
- (void)markPreviousLaunchCrashedIfNeeded;
- (void)bumpLaunchCounter;
- (BOOL)isInSafeMode SWIFT_WARN_UNUSED_RESULT;
- (void)emitSafeModeEvent;
- (void)markSDKDisabled;
- (void)snapshotBinaryImages;
- (BOOL)initFastWriter SWIFT_METHOD_FAMILY(none) SWIFT_WARN_UNUSED_RESULT;
- (void)deliverPendingCrashes;
/// Resolved URL: sandbox iff the configured app id starts with
/// <code>sandbox</code> (case-insensitive). Same heuristic NSure.m uses to set
/// <code>_isProduction</code> and <code>_serverURL</code>. The app id is read from the
/// Objective-C global <code>NSURE_APP_ID</code> via <code>NSureCrashAppIdBridge_currentAppId</code>
/// so production and tests share the same UTF-8 bridge path.
+ (NSString * _Nonnull)reportSdkMsgURL SWIFT_WARN_UNUSED_RESULT;
/// Test-only: pin the appId used for endpoint resolution. Pass nil
/// to clear. Used by the wiring tests.
+ (void)setAppIdOverrideForTests:(NSString * _Nullable)id;
/// Test-only: pin the resolved URL directly. Used by coexistence
/// tests that exercise the full wiring against a stub poster.
+ (void)setReportSdkMsgURLOverrideForTests:(NSString * _Nullable)url;
- (BOOL)installCrashHandlers SWIFT_WARN_UNUSED_RESULT;
- (void)uninstallCrashHandlers;
- (void)emitAppInitDone;
@end

@interface NSureCrashProductionHooks (SWIFT_EXTENSION(nSure))
+ (void)refreshKSCrashUserInfo;
@end

/// Small utility for SDK-wide environment queries.
SWIFT_CLASS_NAMED("NSureEnvironment")
@interface NSureEnvironment : NSObject
/// Returns <code>true</code> when the given app ID denotes a sandbox environment.
/// The heuristic is identical across iOS and Android: a
/// case-insensitive “sandbox” prefix on the app ID string.
+ (BOOL)isSandboxAppId:(NSString * _Nullable)appId SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5nSure23NSureFingerprintManager")
@interface NSureFingerprintManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSureFingerprintManager * _Nonnull shared;)
+ (NSureFingerprintManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
/// Returns the cached requestId, or nil if not yet available or failed.
@property (nonatomic, readonly, copy) NSString * _Nullable currentFpRequestId;
/// True once start() or startWithApiKey(_:) has been called.
@property (nonatomic, readonly) BOOL isStarted;
/// Start fingerprint fetch. Uses the provided remote config key if non-empty,
/// otherwise falls back to the default key. Idempotent — second call is a no-op.
- (void)start;
/// Underlying fetch method. Called by start() in production and directly by tests.
/// \param apiKey FingerprintPro public API key.
///
- (void)startWithApiKey:(NSString * _Nonnull)apiKey;
/// Wait until the fingerprint state settles (.available or .failed), or until
/// <code>timeout</code> seconds elapse — whichever comes first. The completion block is
/// called exactly once on a background queue.
/// If state is already settled when called, <code>completion</code> fires immediately
/// (asynchronously on a global queue to avoid deadlocks).
- (void)waitForReadinessWithTimeout:(NSTimeInterval)timeout completion:(void (^ _Nonnull)(void))completion;
/// When non-nil, called instead of FingerprintProFactory in performFetch.
/// Use in pre-commit / CODE_SIGNING_ALLOWED=NO environments where
/// FingerprintPro’s Keychain init crashes (missing entitlements).
@property (nonatomic, copy) void (^ _Nullable testFetchBlock)(void);
/// Simulate a successful fingerprint fetch result. For unit tests only.
/// Also drains any pending waitForReadiness callbacks.
- (void)testInjectResultWithVisitorId:(NSString * _Nonnull)visitorId requestId:(NSString * _Nonnull)requestId;
/// Simulate a failed fingerprint fetch. For unit tests only.
/// Also drains any pending waitForReadiness callbacks.
- (void)testInjectFailure;
@property (nonatomic, readonly) NSInteger testPendingReadinessCallbackCount;
- (void)testFirePendingReadinessCallbacks;
/// Reset the manager to its initial state. For unit tests only.
/// Discards any pending callbacks without firing them. Preserves
/// <code>testFetchBlock</code> so the next start() call cannot reach real FP.
- (void)testReset;
@end

SWIFT_ENUM_FWD_DECL(NSInteger, NSureLogLevel)
@protocol NSureLogDelegate;
SWIFT_CLASS_NAMED("NSureLog")
@interface NSureLog : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
+ (void)setLogLevel:(enum NSureLogLevel)level;
/// Clear the remote log level override, reverting to the local ceiling.
+ (void)clearRemoteLevel;
+ (void)setLogDelegate:(id <NSureLogDelegate> _Nullable)delegate;
/// Returns true if a message at <code>level</code> would pass the current threshold.
+ (BOOL)isEnabledFor:(enum NSureLogLevel)level SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(NSInteger, NSureLogCategory, open) {
  NSureLogCategoryCore = 0,
  NSureLogCategoryConfig = 1,
  NSureLogCategorySession = 2,
  NSureLogCategoryEvents = 3,
  NSureLogCategoryNetwork = 4,
  NSureLogCategoryFingerprint = 5,
  NSureLogCategoryLifecycle = 6,
  NSureLogCategoryCrash = 7,
  NSureLogCategoryRemoteLog = 8,
};

SWIFT_PROTOCOL("_TtP5nSure16NSureLogDelegate_")
@protocol NSureLogDelegate
- (void)nsureLogWithLevel:(enum NSureLogLevel)level category:(enum NSureLogCategory)category message:(NSString * _Nonnull)message;
@end

typedef SWIFT_ENUM(NSInteger, NSureLogLevel, open) {
  NSureLogLevelOff = -1,
  NSureLogLevelError = 0,
  NSureLogLevelWarning = 1,
  NSureLogLevelInfo = 2,
  NSureLogLevelDebug = 3,
  NSureLogLevelVerbose = 4,
};

SWIFT_CLASS_NAMED("NSureLogObjC")
@interface NSureLogObjC : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// General log method. Guards against invalid enum raw values from ObjC callers.
/// The message parameter is declared optional to safely handle ObjC callers passing nil
/// (which can happen despite nonnull annotations when callers silence the warning).
+ (void)logWithLevel:(enum NSureLogLevel)level category:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logError:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logWarning:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logInfo:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logDebug:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
+ (void)logVerbose:(enum NSureLogCategory)category message:(NSString * _Nullable)message;
@end

@protocol NSureRemoteConfigListener;
@class NSURLSessionConfiguration;
@class NSData;
SWIFT_CLASS("_TtC5nSure23NSureMobileRemoteConfig")
@interface NSureMobileRemoteConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSureMobileRemoteConfig * _Nonnull sharedInstance;)
+ (NSureMobileRemoteConfig * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
/// Register a listener for live config updates. Double-add is a
/// no-op (object identity check). Thread-safe.
- (void)addConfigListener:(id <NSureRemoteConfigListener> _Nonnull)listener;
/// Unregister a previously added listener. Thread-safe.
- (void)removeConfigListener:(id <NSureRemoteConfigListener> _Nonnull)listener;
/// Visible for tests — snapshot the current listener count so tests
/// can assert registration without reaching through reflection.
- (NSInteger)configListenerCountForTests SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, strong) NSureResolvedConfig * _Nonnull resolvedConfig;
@property (nonatomic) BOOL isSDKEnabled;
@property (nonatomic, readonly) BOOL off;
@property (nonatomic, readonly) BOOL merchantOff;
@property (nonatomic, readonly) BOOL platformOff;
@property (nonatomic, readonly) BOOL partnerOff;
- (BOOL)isOff SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull appId;
@property (nonatomic, copy) NSString * _Nonnull partnerId;
/// URLSession configuration used for config fetches.
/// Uses .default so globally registered URLProtocol subclasses are picked up at call time.
@property (nonatomic, strong) NSURLSessionConfiguration * _Nonnull urlSessionConfiguration;
/// Set this before SDK init to bypass network fetch and use a local JSON dictionary.
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable localConfigOverride;
- (void)fetchRemoteConfigWith:(NSString * _Nonnull)appId configUrl:(NSString * _Nullable)configUrl fallbackConfigUrl:(NSString * _Nullable)fallbackConfigUrl completion:(void (^ _Nullable)(void))completion;
- (void)parseRemoteConfig:(NSDictionary<NSString *, id> * _Nonnull)dict;
/// Hard size cap for remote-config payloads. Bodies over this are rejected
/// without parsing to bound memory/CPU on a hostile or misbehaving server.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger maxConfigBytes;)
+ (NSInteger)maxConfigBytes SWIFT_WARN_UNUSED_RESULT;
/// Test-only wrapper that exposes the private parser to ObjC tests.
+ (NSDictionary<NSString *, id> * _Nullable)parseConfigJSONForTesting:(NSData * _Nonnull)data source:(NSString * _Nonnull)source SWIFT_WARN_UNUSED_RESULT;
@end

SWIFT_CLASS("_TtC5nSure19NSureNetworkMonitor")
@interface NSureNetworkMonitor : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSureNetworkMonitor * _Nonnull shared;)
+ (NSureNetworkMonitor * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (void)startMonitoringWithCallback:(void (^ _Nonnull)(BOOL))callback;
@end

/// Listener protocol for subsystems that need to react to remote-config
/// updates at runtime (not just the one-shot post-init callback). Fires
/// after <code>resolvedConfig</code> has been updated and all side-effects inside
/// <code>parseRemoteConfig</code> / <code>loadFromCacheOrMinimumMode</code> have run, on the
/// main thread (the parse path always dispatches to main).
/// Listeners MUST NOT raise — any exception is caught and NSLogged
/// inside <code>fireConfigUpdated(_:)</code> so the config pipeline cannot be
/// broken by a buggy subscriber.
SWIFT_PROTOCOL("_TtP5nSure25NSureRemoteConfigListener_")
@protocol NSureRemoteConfigListener
- (void)onRemoteConfigUpdated:(NSureResolvedConfig * _Nonnull)resolved;
@end

@class NSNumber;
/// Resolved feature configuration after three-level merge.
/// Properties use internal(set) — tests configure state via parseRemoteConfig with JSON dicts.
SWIFT_CLASS("_TtC5nSure19NSureResolvedConfig")
@interface NSureResolvedConfig : NSObject
@property (nonatomic, readonly) BOOL keepAlive;
@property (nonatomic, readonly) BOOL printScreen;
@property (nonatomic, readonly) BOOL fingerprint;
@property (nonatomic, readonly) BOOL sessionTracking;
/// Crash reporting defaults OFF (opt-in): the SDK must NOT install
/// crash handlers until remote config explicitly turns the flag on.
/// Mirrors Android NSureConfigResolver.Feature.CRASH_REPORTING.defaultValue=false.
@property (nonatomic, readonly) BOOL crashReporting;
@property (nonatomic, readonly) BOOL remoteLogging;
@property (nonatomic, readonly) NSInteger keepAliveRolloutPercent;
@property (nonatomic, readonly) NSInteger printScreenRolloutPercent;
@property (nonatomic, readonly) NSInteger fingerprintRolloutPercent;
@property (nonatomic, readonly) NSInteger sessionTrackingRolloutPercent;
@property (nonatomic, readonly) NSInteger crashReportingRolloutPercent;
@property (nonatomic, readonly) NSInteger remoteLoggingRolloutPercent;
@property (nonatomic, readonly) NSInteger appActivationRate;
@property (nonatomic, readonly, copy) NSString * _Nonnull eventsReportUrl;
@property (nonatomic, readonly, copy) NSString * _Nonnull fingerprintApiKey;
/// Remote-config log level. nil means no logLevel was specified in config.
/// Stored as NSNumber wrapping the raw Int of NSureLogLevel because @objc
/// does not support Optional<enum>.
@property (nonatomic, readonly, strong) NSNumber * _Nullable logLevelRaw;
/// Resolved <code>verbosityReportingRate</code>. nil means the feature is inactive
/// (key absent / unparseable / suppressed on kill path). When set, the
/// value is clamped to [0, 100]. Applied as a one-shot session roll at
/// the first config where the key appears.
@property (nonatomic, readonly, strong) NSNumber * _Nullable verbosityReportingRate;
/// Resolver-derived kill-switch booleans. Set to true when the
/// corresponding layer’s <code>off</code> flag was true in the config JSON that
/// produced this resolution. These are the authoritative kill signals
/// consumed by <code>NSureMobileRemoteConfig.applyResolvedSideEffects</code> —
/// they are NOT the persisted flags read back from UserDefaults.
@property (nonatomic, readonly) BOOL globalOff;
@property (nonatomic, readonly) BOOL merchantOff;
@property (nonatomic, readonly) BOOL platformOff;
@property (nonatomic, readonly) BOOL partnerOff;
+ (NSureResolvedConfig * _Nonnull)minimumModeConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5nSure23NSureScreenshotDetector")
@interface NSureScreenshotDetector : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSureScreenshotDetector * _Nonnull shared;)
+ (NSureScreenshotDetector * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Called whenever a screenshot is taken.
@property (nonatomic, copy) void (^ _Nullable onScreenshotTaken)(void);
- (void)startListening;
- (void)stopListening;
@end

SWIFT_CLASS("_TtC5nSure22NSureVersionComparator")
@interface NSureVersionComparator : NSObject
+ (enum NSComparisonResult)compare:(NSString * _Nullable)v1 with:(NSString * _Nullable)v2 SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif // defined(__OBJC__)
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
